//! SurrealDB persistence for CLI runs. Owner-scoped. The row stores the user's
//! prompt and a final result/summary — never verbatim tool bodies.

use uuid::Uuid;

use crate::db::Db;
use crate::error::{AppError, AppResult};

use super::model::CliRunRow;

const RUN_SELECT: &str = "SELECT uuid, owner, prompt, model, tool_scope, status, session_id, \
    conversation_id, num_turns, cost_usd, exit_code, result_text, error, project_id, \
    type::string(created_at) AS created_at, type::string(updated_at) AS updated_at, \
    IF finished_at = NONE THEN NONE ELSE type::string(finished_at) END AS finished_at \
    FROM cli_run";

fn vanished() -> AppError {
    AppError::Internal("cli_run not found immediately after write".into())
}

/// Create a run row in the `running` state. `run_id` is the externally-visible
/// uuid (also used as the registry key + sandbox name) so it is generated by the
/// caller; pass `None` here to mint one.
#[allow(clippy::too_many_arguments)]
pub async fn create_run(
    db: &Db,
    owner: &str,
    run_id: &str,
    prompt: &str,
    model: Option<&str>,
    tool_scope: &str,
    project_id: Option<&str>,
    conversation_id: Option<&str>,
) -> AppResult<CliRunRow> {
    let sql = format!(
        "CREATE cli_run CONTENT {{ uuid: $uuid, owner: $owner, prompt: $prompt, model: $model, \
         tool_scope: $tool_scope, status: \"running\", project_id: $project_id, \
         conversation_id: $conversation_id }}; \
         {RUN_SELECT} WHERE owner = $owner AND uuid = $uuid"
    );
    let mut res = db
        .query(sql)
        .bind(("uuid", run_id.to_string()))
        .bind(("owner", owner.to_string()))
        .bind(("prompt", prompt.to_string()))
        .bind(("model", model.map(str::to_string)))
        .bind(("tool_scope", tool_scope.to_string()))
        .bind(("project_id", project_id.map(str::to_string)))
        .bind(("conversation_id", conversation_id.map(str::to_string)))
        .await?
        .check()?;
    let rows: Vec<CliRunRow> = res.take(1)?;
    rows.into_iter().next().ok_or_else(vanished)
}

/// Mint a fresh run id.
pub fn new_run_id() -> String {
    Uuid::new_v4().to_string()
}

pub async fn get_run(db: &Db, owner: &str, uuid: &str) -> AppResult<Option<CliRunRow>> {
    let sql = format!("{RUN_SELECT} WHERE owner = $owner AND uuid = $uuid");
    let mut res = db
        .query(sql)
        .bind(("owner", owner.to_string()))
        .bind(("uuid", uuid.to_string()))
        .await?
        .check()?;
    Ok(res.take::<Vec<CliRunRow>>(0)?.into_iter().next())
}

pub async fn list_runs(
    db: &Db,
    owner: &str,
    project: Option<&str>,
    status: Option<&str>,
    limit: usize,
    offset: usize,
) -> AppResult<Vec<CliRunRow>> {
    let mut clauses = vec!["owner = $owner".to_string()];
    if project.is_some() {
        clauses.push("project_id = $project".to_string());
    }
    if status.is_some() {
        clauses.push("status = $status".to_string());
    }
    let sql = format!(
        "{RUN_SELECT} WHERE {} ORDER BY created_at DESC LIMIT $limit START $offset",
        clauses.join(" AND ")
    );
    let mut query = db
        .query(sql)
        .bind(("owner", owner.to_string()))
        .bind(("limit", limit as i64))
        .bind(("offset", offset as i64));
    if let Some(p) = project {
        query = query.bind(("project", p.to_string()));
    }
    if let Some(s) = status {
        query = query.bind(("status", s.to_string()));
    }
    let mut res = query.await?.check()?;
    Ok(res.take(0)?)
}

/// Terminal fields written when a run ends.
#[derive(Default)]
pub struct RunOutcome {
    pub status: String,
    pub session_id: Option<String>,
    pub num_turns: i64,
    pub cost_usd: Option<f64>,
    pub exit_code: Option<i64>,
    pub result_text: Option<String>,
    pub error: Option<String>,
}

/// Fail every run still marked `running` (all owners). Called once at startup:
/// runs are driven by process-local tasks, so a row left `running` from a
/// previous process is an orphan that would otherwise look live forever.
pub async fn fail_orphaned_runs(db: &Db) -> AppResult<usize> {
    let mut res = db
        .query(
            "UPDATE cli_run SET status = 'failed', \
             error = 'interrupted by a server restart', \
             finished_at = time::now() WHERE status = 'running' RETURN AFTER",
        )
        .await?
        .check()?;
    let rows: Vec<CliRunRow> = res.take(0)?;
    Ok(rows.len())
}

/// Record a run's terminal state, stamping `finished_at`.
pub async fn finalize_run(db: &Db, owner: &str, uuid: &str, outcome: &RunOutcome) -> AppResult<()> {
    db.query(
        "UPDATE cli_run SET status = $status, session_id = $sid, num_turns = $turns, \
         cost_usd = $cost, exit_code = $exit, result_text = $rt, error = $err, \
         finished_at = time::now() WHERE owner = $owner AND uuid = $uuid",
    )
    .bind(("owner", owner.to_string()))
    .bind(("uuid", uuid.to_string()))
    .bind(("status", outcome.status.clone()))
    .bind(("sid", outcome.session_id.clone()))
    .bind(("turns", outcome.num_turns))
    .bind(("cost", outcome.cost_usd))
    .bind(("exit", outcome.exit_code))
    .bind(("rt", outcome.result_text.clone()))
    .bind(("err", outcome.error.clone()))
    .await?
    .check()?;
    Ok(())
}
